/** @type {import('next').NextConfig} */
const fs = require('fs')
const path = require('path')

// Load per-customer build fingerprint (generated by scripts/build-inject.js)
// Falls back gracefully if file doesn't exist (dev mode)
let buildEnv = {}
const buildEnvPath = path.join(__dirname, '.env.build')
if (fs.existsSync(buildEnvPath)) {
  const lines = fs.readFileSync(buildEnvPath, 'utf8').split('\n')
  for (const line of lines) {
    if (line.startsWith('#') || !line.includes('=')) continue
    const [k, ...v] = line.split('=')
    buildEnv[k.trim()] = v.join('=').trim()
  }
}

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: 'standalone',
  images: {
    domains: ['localhost'],
  },
  env: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000',
    // Layer 2: Per-customer build fingerprint (injected at build time)
    NEXT_PUBLIC_BUILD_FINGERPRINT: buildEnv.NEXT_PUBLIC_BUILD_FINGERPRINT || 'DEV-00000000',
    NEXT_PUBLIC_BUILD_CUSTOMER: buildEnv.NEXT_PUBLIC_BUILD_CUSTOMER || 'DEV',
  },
  transpilePackages: ['react-leaflet'],
}

module.exports = nextConfig
