/**
 * Build Fingerprint Injection Script
 * Run before `next build` to embed per-customer fingerprint into the bundle.
 *
 * Usage:
 *   node scripts/build-inject.js <CUSTOMER_ID>
 *   node scripts/build-inject.js BANK_ABC
 *
 * Then build:
 *   npm run build
 *   # or
 *   CUSTOMER_ID=BANK_ABC npm run build:customer
 *
 * The fingerprint is embedded into:
 *   - process.env.NEXT_PUBLIC_BUILD_FINGERPRINT  (in JS bundle)
 *   - process.env.NEXT_PUBLIC_BUILD_CUSTOMER     (in JS bundle)
 *   - process.env.BUILD_FINGERPRINT              (for backend env)
 *   - process.env.BUILD_CUSTOMER                 (for backend env)
 *
 * IMPORTANT: .env.build is gitignored — never commit it.
 */

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const customerId = (process.argv[2] || process.env.CUSTOMER_ID || 'DEV').toUpperCase()
const buildId = crypto.randomBytes(8).toString('hex')
const fingerprint = `${customerId}-${buildId}`
const buildDate = new Date().toISOString()

const envContent = [
  `# Auto-generated by build-inject.js — DO NOT COMMIT`,
  `# Customer: ${customerId}`,
  `# Generated: ${buildDate}`,
  ``,
  `NEXT_PUBLIC_BUILD_FINGERPRINT=${fingerprint}`,
  `NEXT_PUBLIC_BUILD_CUSTOMER=${customerId}`,
  `BUILD_FINGERPRINT=${fingerprint}`,
  `BUILD_CUSTOMER=${customerId}`,
  `BUILD_DATE=${buildDate}`,
].join('\n')

const envPath = path.join(__dirname, '..', '.env.build')
fs.writeFileSync(envPath, envContent, 'utf8')

// Also log to a build manifest for your records (gitignored)
const manifestPath = path.join(__dirname, '..', 'build-manifest.jsonl')
const entry = JSON.stringify({ fingerprint, customerId, buildDate }) + '\n'
fs.appendFileSync(manifestPath, entry, 'utf8')

console.log('╔═══════════════════════════════════════════╗')
console.log('║        Build Fingerprint Injected         ║')
console.log('╠═══════════════════════════════════════════╣')
console.log(`║  Customer  : ${customerId.padEnd(28)}║`)
console.log(`║  Build ID  : ${buildId.padEnd(28)}║`)
console.log(`║  Fingerprint: ${fingerprint.padEnd(27)}║`)
console.log('╚═══════════════════════════════════════════╝')
